version: '3'
services:
    jekyll-serve:
        image: jekyll/minimal:pages
        volumes:
            - '.:/srv/jekyll:cached'
        ports:
            - 4000:4000
        command: 'jekyll serve --watch --force_polling'