version: '3'
services:
    jekyll-serve:
        image: jekyll/minimal:latest
        volumes:
            - '.:/srv/jekyll:cached'
        ports:
            - 4000:4000
        command: > 
            bash -c "cd /srv/jekyll && 
                    sh install-gems.sh && 
                    jekyll serve --watch --force_polling --config _config.dev.yml"